name: Pipeline Calculadora TDD

on: [push, pull_request]

jobs:

  pruebas:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Ejecutar pruebas unitarias
        run: |
          pytest